var players = [
  { name: "Lionel Messi", club: "Inter de Miami", country: "Argentina" },
  { name: "Cristiano Ronaldo", club: "Al Nassr", country: "Portugal" },
  { name: "Neymar Jr", club: "Al Hilal", country: "Brasil" },
  { name: "Kylian Mbappé", club: "Paris Sain Germain", country: "Francia" },
  { name: "Mohamed Salah", club: "Liverpool", country: "Egipto" },
  { name: "Sadio Mané", club: "Al Nassr", country: "Senegal" },
  { name: "Kevin De Bruyne", club: "Manchester City", country: "Bélgica" },
  { name: "Robert Lewandowski", club: "Barcelona", country: "Polonia" },
  { name: "Sergio Ramos", club: "sevilla", country: "España" },
  { name: "Virgil van Dijk", club: "Liverpool", country: "Holanda" },
  { name: "Karim Benzema", club: "Al Itihad", country: "Francia" },
  { name: "Luka Modric", club: "Real Madrid", country: "Croacia" },
  { name: "Harry Kane", club: "Bayern Munich", country: "Inglaterra" },
  { name: "Vinicius Jr", club: "Real Madrid", country: "Brasil" },
  { name: "Erling Haaland", club: "Manchester City", country: "Noruega" },
  { name: "Bruno Fernandes", club: "Manchester United", country: "Portugal" },
  { name: "Joshua Kimmich", club: "Bayern Munich", country: "Alemania" },
  { name: "Ciro Immobile", club: "Lazio", country: "Italia" },
  { name: "Romelu Lukaku", club: "Chelsea", country: "Bélgica" },
  { name: "Jadon Sancho", club: "Manchester United", country: "Inglaterra" },
  { name: "Raheem Sterling", club: "Manchester City", country: "Inglaterra" },
  {
    name: "Gianluigi Donnarumma",
    club: "Paris Saint Germain",
    country: "Italia",
  },
  { name: "Alisson Becker", club: "Liverpool", country: "Brasil" },
  { name: "Thibaut Courtois", club: "Real Madrid", country: "Bélgica" },
  { name: "Ederson Moraes", club: "Manchester City", country: "Brasil" },
  { name: "Marc-André ter Stegen", club: "Barcelona", country: "Alemania" },
  { name: "Jan Oblak", club: "Atlético de Madrid", country: "Esloven" },
];
