var teams = [
  {
    name: "Real Madrid",
    country: "Spain",
    league: "La Liga",
    championsLeague: 14,
  },
  {
    name: "Barcelona",
    country: "Spain",
    league: "La Liga",
    championsLeague: 5,
  },
  {
    name: "Bayern Múnich",
    country: "Germany",
    league: "Bundesliga",
    championsLeague: 6,
  },
  {
    name: "Borussia Dortmund",
    country: "Germany",
    league: "Bundesliga",
    championsLeague: 1,
  },
  {
    name: "Milan",
    country: "Italy",
    league: "Serie A",
    championsLeague: 7,
  },
  {
    name: "Juventus",
    country: "Italy",
    league: "Serie A",
    championsLeague: 2,
  },
  {
    name: "Inter de Milán",
    country: "Italy",
    league: "Serie A",
    championsLeague: 3,
  },
  {
    name: "Chelsea",
    country: "England",
    league: "Premier League",
    championsLeague: 1,
  },
  {
    name: "Liverpool",
    country: "England",
    league: "Premier League",
    championsLeague: 6,
  },
  {
    name: "Manchester United",
    country: "England",
    league: "Premier League",
    championsLeague: 3,
  },
  {
    name: "arsenal",
    country: "England",
    league: "Premier League",
    championsLeague: 0,
  },
  {
    name: "Manchester City",
    country: "England",
    league: "Premier League",
    championsLeague: 0,
  },
  {
    name: "totenham",
    country: "England",
    league: "Premier League",
    championsLeague: 0,
  },
  {
    name: "Porto",
    country: "Portugal",
    league: "Primeira Liga",
    championsLeague: 2,
  },
  {
    name: "Benfica",
    country: "Portugal",
    league: "Primeira Liga",
    championsLeague: 2,
  },
  {
    name: "Ajax",
    country: "Netherlands",
    league: "Eredivisie",
    championsLeague: 4,
  },
  {
    name: "PSV Eindhoven",
    country: "Netherlands",
    league: "Eredivisie",
    championsLeague: 1,
  },
  {
    name: "Paris Saint-Germain",
    country: "France",
    league: "Ligue 1",
    championsLeague: 0,
  },
  {
    name: "Olympique de Lyon",
    country: "France",
    league: "Ligue 1",
    championsLeague: 0,
  },
  {
    name: "Marsella",
    country: "France",
    league: "Ligue 1",
    championsLeague: 1,
  },
];
